config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  resources :dashboards do
    collection do
      get :online
    end
  end

  namespace :research do
    resources :rtc_connections do
      collection do
        get :live_broadcast
        get :live_streaming
        post :synchronization
        post :broadcast
      end
    end

    resources :synchronization
  end

  namespace :web do
    resources :chats do
      collection do
        get  :load_room
        post :publish
      end
    end

    resources :groups
    resources :profiles
  end

  namespace :admin do
    resources :categories
  end

  namespace :api do
    resources :syncs, path: "sync" do
      collection do
        post :call
      end
    end

    resources :categories do
      collection do
        get :main_category
      end
    end
    
    resources :chats do
      collection do
        post :chatroom
        post :publish
        post :image
        post :video
        post :voice
        post :file
      end
    end

    resources :groups do
      collection do
        post :chatroom
        post :publish
      end
      
      member do
        post :register
        post :select
      end
    end
    
    resources :users do
      collection do
        post :member
        post :status
        post :resend
        get :otp
      end

      member do
        post :register
        post :device_token
        post :avatar
        get :contact
      end
    end

    resources :notes do
      collection do
        post :create
        post :story_like
        post :story_comment
        get :index
      end

      member do
        post :notes_group
      end
    end
  end

  resources :message_groups
  resources :messages
  resources :groups
  resources :users
  resources :conversations
  
  root "dashboards#index"
  mount ActionCable.server, at: '/cable'
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
  has_many :attachments

  # after_save :reload_page

  def reload_page
    user = User.find(self.user_to)
    recent   = JSON.parse(user.recent_chat)
    users    = JSON.parse(user.contact_list)
    messages = Message.conversations(self.user_id, self.user_to)
    
    html_recent = ApplicationController.render partial: "conversations/recent", locals: {recent: recent, user: self.user}, formats: [:html]
    html_messages = ApplicationController.render partial: "conversations/messages", locals: {messages: messages, user: user}, formats: [:html]

    ActionCable.server.broadcast "from_#{self.user_to}:to_#{self.user_id}", {html: {recent: html_recent, messages: html_messages}}
  end

  class << self
    def chat(user, user_to, params)
      message = user.messages.new
      message.user_to = user_to.id
      message.content = params[:content]

      if message.save
        return { data: message, message: "success" }
      else
        return { data: message, message: message.errors }
      end
    end

    def conversations(from, to)
      where("(user_id = #{from} AND user_to = #{to}) OR (user_id = #{to} AND user_to = #{from})").order(:created_at)
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:user_id, :user_to, :content)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :user_to %>
    <%= form.number_field :user_to %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>User to</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.user_id %></td>
        <td><%= message.user_to %></td>
        <td><%= message.content %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @message.user_id %>
</p>

<p>
  <strong>User to:</strong>
  <%= @message.user_to %>
</p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>