config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  resources :dashboards do
    collection do
      get :online
    end
  end

  namespace :research do
    resources :rtc_connections do
      collection do
        get :live_broadcast
        get :live_streaming
        post :synchronization
        post :broadcast
      end
    end

    resources :synchronization
  end

  namespace :web do
    resources :chats do
      collection do
        get  :load_room
        post :publish
      end
    end

    resources :groups
    resources :profiles
  end

  namespace :admin do
    resources :categories
  end

  namespace :api do
    resources :syncs, path: "sync" do
      collection do
        post :call
      end
    end

    resources :categories do
      collection do
        get :main_category
      end
    end
    
    resources :chats do
      collection do
        post :chatroom
        post :publish
        post :image
        post :video
        post :voice
        post :file
      end
    end

    resources :groups do
      collection do
        post :chatroom
        post :publish
      end
      
      member do
        post :register
        post :select
      end
    end
    
    resources :users do
      collection do
        post :member
        post :status
        post :resend
        get :otp
      end

      member do
        post :register
        post :device_token
        post :avatar
        get :contact
      end
    end

    resources :notes do
      collection do
        post :create
        post :story_like
        post :story_comment
        get :index
      end

      member do
        post :notes_group
      end
    end
  end

  resources :message_groups
  resources :messages
  resources :groups
  resources :users
  resources :conversations
  
  root "dashboards#index"
  mount ActionCable.server, at: '/cable'
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :check_web_session, only: [:index]

  def index
    @session = Session.prepare
    @qr_code = QrCode.generate(Setting::BASE_URL + session_path(@session[:data].id), @session[:data].sign_id)

    cookies[:web_version_identify] = @session[:data].sign_id
  end

  def online; end

  def create
    @user = User.find_or_create_by(phone: params[:phone])
    @user.name = params[:name]

    if @user.save
      @session = Session.prepare[:data]
      @session = @session.write(@user.phone, request.remote_ip)
      session[:sign_id] = @session[:data].sign_id
      cookies[:phone_number] = @user.phone
      session[:phone_number] = @user.phone

      redirect_to web_chats_path, notice: "You are online now"
    else
      redirect_to root_path, notice: "Online access failed"
    end
  end

  private
  def access_params
    params.permit(:phone, :name)
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/index.html.haml
%nav.navbar.navbar-light.bg-blue-light
  .container
    %a.navbar-brand.navbar-brand-costum
      = image_tag "logo.png", height: 40
      ChatU

.container.init-card
  .card
    .card-body
      .row
        .col-8
          .card-block
            %h3.title
              To use ChatU on your computer :
            %ol
              %li Open ChatU on your phone
              %li Tap menu Settings and select ChatU Web
              %li Point your phone to this screen to capture the code
            %hr
            = link_to "Need help to get started?", "#"
            or
            = link_to "Try new online version?", online_dashboards_path
        .col-4
          = image_tag @qr_code[:data], class: "qr-code"

app/views/dashboards/online.html.haml
%nav.navbar.navbar-light.bg-blue-light
  .container
    %a.navbar-brand.navbar-brand-costum
      = image_tag "logo.png", height: 40
      ChatU

.container.init-card
  .card
    .card-body
      .row
        .col-8
          .card-block
            %h3.title
              To use online ChatU on your computer :
            %ol
              %li Type your phone number
              %li Invite friend to join
            %hr
            = link_to "Go back", root_path
        .col-4
          .form-box
            = form_tag dashboards_path do
              .form-group
                = label_tag :phone, "Phone Number :"
                = number_field_tag :phone, nil, placeholder: "Phone Number", class: "form-control"
              .form-group
                = label_tag :name, "Your Name :"
                = text_field_tag :name, nil, placeholder: "Your Name", class: "form-control"
              .form-group.text-right
                = submit_tag "Sign in now", class: "btn btn-info"